BEGIN;

drop table if exists bookmarks;

create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title text,
    url VARCHAR(30),
    rating VARCHAR(30),
    description text 
);

INSERT INTO bookmarks (title, url, rating, description)
VALUES
  ('Thinkful', 'https://www.thinkful.com', '5', 'Think outside the classroom'),
  ('Google', 'https://www.google.com', '4', 'Where we find everything else'),
  ('MDN', 'https://developer.mozilla.org', '5', 'The only place to find web documentation');

  COMMIT;